<?php
$customerId = Mage::helper('creditpoint')->getCurrentCustomerId();
$customerCreditPoints = Mage::helper('creditpoint')->getCustomerCreditPointsAssigned();
$customerCollection = $this->getCollection();
?>

<?php $currentCurrency = Mage::helper('creditpoint')->getCurrentCurrencySymbol(); ?>
<?php $creditPoints = Mage::helper('creditpoint')->getFormatCreditPoint($customerCreditPoints); ?>
<?php $currentPointAmount = number_format(Mage::helper('creditpoint')->getPointCurrencyAmount($creditPoints), 2, '.', ''); ?>
<?php $finalRatio = Mage::helper('creditpoint')->getPointCurrencyRatio(); ?>
<?php $finalEarnedPointsRatio = Mage::helper('creditpoint')->getEarnedPointsRatio(); ?>


<div class="box-account">
    <div class="box-head">
        <h2><?php echo $this->__('Credit Points Information') ?></h2>
    </div>

    <div>
        <?php echo $this->__('Your Credit Points'); ?>:&nbsp;
        <strong><?php echo $creditPoints; ?>&nbsp;<?php echo $this->__('Points'); ?>&nbsp;=&nbsp;<?php echo $currentCurrency; ?><?php echo $currentPointAmount; ?></strong>
    </div>
    <br/>
    <div>
        <?php echo $this->__('Points/Currency Exchange Rate'); ?>:&nbsp;<strong><?php echo $finalRatio; ?></strong>
    </div>
    <br/>
    <div>
        <?php echo $finalEarnedPointsRatio; ?>
    </div>

</div>


<!--Credit Points Transaction History Starts-->
<?php if ($customerCollection->getSize()): ?>

    <?php echo $this->getPagerHtml(); ?>
    <div class="box-account">
        <div class="head box-head">
            <h2>Credit Points Transaction History</h2>
            <a href="javascript:void(0)" id="transaction_box_hander">Hide</a>
        </div>
        <div id="transaction_history_box" style="display: block;">
            <table id="creditpoint-transaction-table" class="data-table">
                <colgroup>
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                    <col width="1" />
                </colgroup>
                <thead>
                    <tr class="first last">
                        <th style="text-align: center;"><?php echo $this->__('Order #'); ?></th>
                        <th style="text-align: center;"><?php echo $this->__('Date'); ?></th>
                        <th style="text-align: center;"><?php echo $this->__('Points Redeemed'); ?></th>
                        <th style="text-align: center;"><?php echo $this->__('Points Price'); ?></th>
                        <th style="text-align: center;"><?php echo $this->__('Points Earned'); ?></th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    foreach ($customerCollection as $collection):

                        $order = Mage::getModel('sales/order')->load($collection->getOrderId());
                        $orderUrl = Mage::helper('creditpoint')->getOrderUrl($order->getEntityId());
                        $orderDate = date('m/d/Y', strtotime($collection->getCreatedTime()));
                        if ($collection->getEarnedCreditPoint() != 0):
                    ?>

                            <tr class="first odd">
                                <td style="text-align: center;"><a href="<?php echo $orderUrl; ?>" target="_blank"><?php echo $order->getIncrementId(); ?></a>
                                <td style="text-align: center;"><?php echo $orderDate; ?>
                                <td style="text-align: center;"><?php echo number_format($collection->getAppliedCreditPoint()); ?>
                                <td style="text-align: center;"><?php echo Mage::helper('creditpoint')->getCurrentCurrencySymbol(); ?><?php echo $collection->getAppliedCreditPointPrice(); ?>
                                <td style="text-align: center;"><?php echo number_format($collection->getEarnedCreditPoint()); ?>
                            </tr>

                        <?php else: ?>

                            <tr class="first odd">
                                <td style="text-align: center;"><a href="<?php echo $orderUrl; ?>" target="_blank"><?php echo $order->getIncrementId(); ?></a>
                                <td style="text-align: center;"><?php echo $orderDate; ?>
                                <td style="text-align: center;"><?php echo number_format($collection->getAppliedCreditPoint()); ?>
                                <td style="text-align: center;"><?php echo Mage::helper('creditpoint')->getCurrentCurrencySymbol(); ?><?php echo $collection->getAppliedCreditPointPrice(); ?>
                                <td style="text-align: center;"><?php echo $this->__('-'); ?>
                            </tr>

                        <?php endif; ?>

                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <script type="text/javascript">decorateTable('creditpoint-transaction-table')</script>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php endif; ?>
<!--Credit Points Transaction History Ends-->

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account/') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>

<script type="text/javascript">
    $('transaction_box_hander').observe('click', function(event) {
        Effect.toggle('transaction_history_box', 'slide');
        if ($('transaction_history_box').visible()) {
            $('transaction_box_hander').update('Show');
        } else {
            $('transaction_box_hander').update('Hide');
        }
        Event.stop(event);
    });
</script>