<script type="text/javascript">
	
	$clickview(document).ready(function(){
		
		var slider = $clickview('.bxslider_clickview_most_viewed_by_category').bxSlider({
		  
		  mode: '<?php echo $this->getMostViewedByCatMode() ?>',
		  minSlides:   <?php echo $this->getMinSlides() ?>,
		  maxSlides:   <?php echo $this->getMaxSlides() ?>,
		  slideWidth:  <?php echo $this->getSlideWidth() ?>,
		  slideMargin: <?php echo $this->getSlideMargin() ?>
		    
		});
		
		var formData1 = {
		    			cat : <?php echo $this->getCatDefault(); ?>,
		    		};
		
		$clickview.ajax({	
				
			url: "<?php echo $this->getUrlControllerMostViewedByCategory() ?>",
			type: "POST",
		    dataType: 'json',
		    cache : false,
		    data: formData1,
		    beforeSend: function(){
		    	$clickview('.bxslider_clickview_most_viewed_by_category').append('<li><img src="<?php echo Mage::getBaseUrl() ?>/skin/frontend/base/default/jefferson/Clickview/image/loading.gif" /></li>');
		    },
		    success : function(data2){
		    	$clickview('.bxslider_clickview_most_viewed_by_category').empty();
		    	$clickview('.bxslider_clickview_most_viewed_by_category').append(data2.content);
		    	slider.reloadSlider();
		    },
		    
		});
		
		$clickview('.category_clickview').change(function(){
			
			var formData = {
		    			cat : $clickview('.category_clickview').val(),
		    		};
			
			$clickview.ajax({	
				
				url: "<?php echo $this->getUrlControllerMostViewedByCategory() ?>",
				type: "POST",
			    dataType: 'json',
			    cache : false,
			    data: formData,
			    beforeSend: function(){
			    	$clickview('.bxslider_clickview_most_viewed_by_category').append('<li><img src="<?php echo Mage::getBaseUrl() ?>/skin/frontend/base/default/jefferson/Clickview/image/loading.gif" /></li>');
			    },
			    success : function(data2){
			    	$clickview('.bxslider_clickview_most_viewed_by_category').empty();
			    	$clickview('.bxslider_clickview_most_viewed_by_category').append(data2.content);
			    	slider.reloadSlider();
			    },
			    
			});
			
			
			
		});	
	});
	
</script>

<div class="col-md-3">
	<div class="info">
		<h2 class="subtitle"><?php echo $this->__('Most viewed') ?></h2>
		<select name="category_clickview" class="category_clickview form-control">
			<?php  echo $this->getCategoryMostViewed(); ?>
		</select>
		<ul class="bxslider_clickview_most_viewed_by_category "></ul>
	</div>
</div>
